// Idox Public Access planning portals.
// Registry generated from the PlanIt API (/api/areas/json?area_type=planning), including
// only authorities whose scraper_type mentions Idox AND whose planning_url uses the
// classic Idox "search.do?action=advanced" entry point. baseUrl is the planning_url with
// that search path stripped.
//
// Note: PlanIt's scraper_type labels are unreliable (e.g. Manchester and Powys are labelled
// Idox but run Arcus portals, which is why we also require the search.do URL pattern).
// Many authorities share a portal (e.g. Cambridge City & South Cambridgeshire), so entries
// are deduplicated by baseUrl and alternate area names are kept as aliases.

import type { AuthorityConfig } from './types.js';

export const DEFAULT_AUTHORITY_ID = 'cambridge';

export const AUTHORITIES: AuthorityConfig[] = [
  { id: 'fenland', name: 'Fenland', baseUrl: 'https://www.publicaccess.fenland.gov.uk/publicaccess' },
  { id: 'stockton-on-tees', name: 'Stockton-on-Tees', baseUrl: 'https://www.developmentmanagement.stockton.gov.uk/online-applications' },
  { id: 'darlington', name: 'Darlington', baseUrl: 'https://publicaccess.darlington.gov.uk/online-applications' },
  { id: 'halton', name: 'Halton', baseUrl: 'https://pa.halton.gov.uk/online-applications' },
  { id: 'blackpool', name: 'Blackpool', baseUrl: 'https://idoxpa.blackpool.gov.uk/online-applications' },
  { id: 'hull', name: 'Hull', baseUrl: 'https://www.hullcc.gov.uk/padcbc/publicaccess-live' },
  { id: 'east-riding', name: 'East Riding', baseUrl: 'https://newplanningaccess.eastriding.gov.uk/newplanningaccess' },
  { id: 'north-east-lincs', name: 'North East Lincs', baseUrl: 'https://planninganddevelopment.nelincs.gov.uk/online-applications' },
  { id: 'york', name: 'York', baseUrl: 'https://planningaccess.york.gov.uk/online-applications' },
  { id: 'derby', name: 'Derby', baseUrl: 'https://eplanning.derby.gov.uk/online-applications' },
  { id: 'rutland', name: 'Rutland', baseUrl: 'https://publicaccess.rutland.gov.uk/online-applications' },
  { id: 'nottingham', name: 'Nottingham', baseUrl: 'https://publicaccess.nottinghamcity.gov.uk/online-applications' },
  { id: 'bristol', name: 'Bristol', baseUrl: 'https://pa.bristol.gov.uk/online-applications' },
  { id: 'north-somerset', name: 'North Somerset', baseUrl: 'https://planning.n-somerset.gov.uk/online-applications' },
  { id: 'south-gloucestershire', name: 'South Gloucestershire', baseUrl: 'https://developments.southglos.gov.uk/online-applications' },
  { id: 'plymouth', name: 'Plymouth', baseUrl: 'https://planning.plymouth.gov.uk/online-applications' },
  { id: 'torbay', name: 'Torbay', baseUrl: 'https://publicaccess.torbay.gov.uk/view' },
  { id: 'swindon', name: 'Swindon', baseUrl: 'https://pa.swindon.gov.uk/publicaccess' },
  { id: 'luton', name: 'Luton', baseUrl: 'https://planning.luton.gov.uk/online-applications' },
  { id: 'southend', name: 'Southend', baseUrl: 'https://publicaccess.southend.gov.uk/online-applications' },
  { id: 'thurrock', name: 'Thurrock', baseUrl: 'https://regs.thurrock.gov.uk/online-applications' },
  { id: 'medway', name: 'Medway', baseUrl: 'https://publicaccess1.medway.gov.uk/online-applications' },
  { id: 'west-berkshire', name: 'West Berkshire', baseUrl: 'https://publicaccess.westberks.gov.uk/online-applications' },
  { id: 'windsor', name: 'Windsor', baseUrl: 'https://publicaccess.rbwm.gov.uk/online-applications' },
  { id: 'brighton', name: 'Brighton', baseUrl: 'https://planningapps.brighton-hove.gov.uk/online-applications' },
  { id: 'portsmouth', name: 'Portsmouth', baseUrl: 'https://publicaccess.portsmouth.gov.uk/online-applications' },
  { id: 'southampton', name: 'Southampton', baseUrl: 'https://planningpublicaccess.southampton.gov.uk/online-applications' },
  { id: 'isle-of-wight', name: 'Isle of Wight', baseUrl: 'https://publicaccess.iow.gov.uk/online-applications' },
  { id: 'northumberland-county', name: 'Northumberland (County)', baseUrl: 'https://publicaccess.northumberland.gov.uk/online-applications' },
  { id: 'chester', name: 'Chester', baseUrl: 'https://pa.cheshirewestandchester.gov.uk/online-applications' },
  { id: 'shropshire', name: 'Shropshire', baseUrl: 'https://pa.shropshire.gov.uk/online-applications' },
  { id: 'cornwall', name: 'Cornwall', baseUrl: 'https://planning.cornwall.gov.uk/online-applications' },
  { id: 'bedford', name: 'Bedford', baseUrl: 'https://publicaccess.bedford.gov.uk/online-applications' },
  { id: 'aylesbury-vale', name: 'Aylesbury Vale', baseUrl: 'https://publicaccess.aylesburyvaledc.gov.uk/online-applications' },
  { id: 'wycombe', name: 'Wycombe', baseUrl: 'https://publicaccess.wycombe.gov.uk/idoxpa-web' },
  { id: 'cambridge', name: 'Greater Cambridge', aliases: ['South Cambridgeshire'], baseUrl: 'https://applications.greatercambridgeplanning.org/online-applications', map: { wfsUrl: 'https://applications.greatercambridgeplanning.org/PAM/LIVE/MapServer', layers: ['Planning_Application_Points', 'Planning_Application_Polygons'], refField: 'REFVAL' } },
  { id: 'east-cambridgeshire', name: 'East Cambridgeshire', baseUrl: 'https://pa.eastcambs.gov.uk/online-applications' },
  { id: 'durham', name: 'Durham', baseUrl: 'https://publicaccess.durham.gov.uk/online-applications' },
  { id: 'huntingdonshire', name: 'Huntingdonshire', baseUrl: 'https://publicaccess.huntingdonshire.gov.uk/online-applications' },
  { id: 'carlisle', name: 'Carlisle', baseUrl: 'https://publicaccess.carlisle.gov.uk/online-applications' },
  { id: 'bolsover', name: 'Bolsover', baseUrl: 'https://publicaccess.bolsover.gov.uk/online-applications' },
  { id: 'chesterfield', name: 'Chesterfield', baseUrl: 'https://publicaccess.chesterfield.gov.uk/online-applications' },
  { id: 'derbyshire-dales', name: 'Derbyshire Dales', baseUrl: 'https://planning.derbyshiredales.gov.uk/online-applications' },
  { id: 'north-east-derbyshire', name: 'North East Derbyshire', baseUrl: 'https://planapps-online.ne-derbyshire.gov.uk/online-applications' },
  { id: 'east-devon', name: 'East Devon', baseUrl: 'https://planning.eastdevon.gov.uk/online-applications' },
  { id: 'exeter', name: 'Exeter', baseUrl: 'https://publicaccess.exeter.gov.uk/online-applications' },
  { id: 'mid-devon', name: 'Mid Devon', baseUrl: 'https://planning.middevon.gov.uk/online-applications' },
  { id: 'braintree', name: 'Braintree', baseUrl: 'https://publicaccess.braintree.gov.uk/online-applications' },
  { id: 'brentwood', name: 'Brentwood', baseUrl: 'https://publicaccess.brentwood.gov.uk/online-applications' },
  { id: 'castle-point', name: 'Castle Point', baseUrl: 'https://publicaccess.castlepoint.gov.uk/online-applications' },
  { id: 'chelmsford', name: 'Chelmsford', baseUrl: 'https://publicaccess.chelmsford.gov.uk/online-applications' },
  { id: 'harlow', name: 'Harlow', baseUrl: 'https://planningonline.harlow.gov.uk/online-applications' },
  { id: 'maldon', name: 'Maldon', baseUrl: 'https://publicaccess.maldon.gov.uk/online-applications' },
  { id: 'tendring', name: 'Tendring', baseUrl: 'https://idox.tendringdc.gov.uk/online-applications' },
  { id: 'uttlesford', name: 'Uttlesford', baseUrl: 'https://publicaccess.uttlesford.gov.uk/online-applications' },
  { id: 'tewkesbury', name: 'Tewkesbury', baseUrl: 'https://publicaccess.tewkesbury.gov.uk/online-applications' },
  { id: 'gosport', name: 'Gosport', baseUrl: 'https://publicaccess.gosport.gov.uk/online-applications' },
  { id: 'hart', name: 'Hart', baseUrl: 'https://publicaccess.hart.gov.uk/online-applications' },
  { id: 'new-forest-district', name: 'New Forest (District)', baseUrl: 'https://planning.newforest.gov.uk/online-applications' },
  { id: 'rushmoor', name: 'Rushmoor', baseUrl: 'https://publicaccess.rushmoor.gov.uk/online-applications' },
  { id: 'test-valley', name: 'Test Valley', baseUrl: 'https://view-applications.testvalley.gov.uk/online-applications' },
  { id: 'winchester', name: 'Winchester', baseUrl: 'https://planningapps.winchester.gov.uk/online-applications' },
  { id: 'dacorum', name: 'Dacorum', baseUrl: 'https://planning.dacorum.gov.uk/publicaccess' },
  { id: 'east-hertfordshire', name: 'East Hertfordshire', baseUrl: 'https://publicaccess.eastherts.gov.uk/online-applications' },
  { id: 'hertsmere', name: 'Hertsmere', baseUrl: 'https://www6.hertsmere.gov.uk/online-applications' },
  { id: 'north-hertfordshire', name: 'North Hertfordshire', baseUrl: 'https://pa2.north-herts.gov.uk/online-applications' },
  { id: 'teignbridge', name: 'Teignbridge', baseUrl: 'https://publicaccess.teignbridge.gov.uk/online-applications' },
  { id: 'torridge', name: 'Torridge', baseUrl: 'https://publicaccess.torridge.gov.uk/online-applications' },
  { id: 'cheltenham', name: 'Cheltenham', baseUrl: 'https://publicaccess.cheltenham.gov.uk/online-applications' },
  { id: 'cotswold', name: 'Cotswold', baseUrl: 'https://publicaccess.cotswold.gov.uk/online-applications' },
  { id: 'forest-of-dean', name: 'Forest of Dean', baseUrl: 'https://publicaccess.fdean.gov.uk/online-applications' },
  { id: 'gloucester', name: 'Gloucester', baseUrl: 'https://publicaccess.gloucester.gov.uk/online-applications' },
  { id: 'stroud', name: 'Stroud', baseUrl: 'https://publicaccess.stroud.gov.uk/online-applications' },
  { id: 'hastings', name: 'Hastings', baseUrl: 'https://publicaccess.hastings.gov.uk/online-applications' },
  { id: 'lewes', name: 'Lewes', baseUrl: 'https://planningpa.lewes-eastbourne.gov.uk/online-applications' },
  { id: 'basildon', name: 'Basildon', baseUrl: 'https://planning.basildon.gov.uk/online-applications' },
  { id: 'stevenage', name: 'Stevenage', baseUrl: 'https://publicaccess.stevenage.gov.uk/online-applications' },
  { id: 'three-rivers', name: 'Three Rivers', baseUrl: 'https://www3.threerivers.gov.uk/online-applications' },
  { id: 'watford', name: 'Watford', baseUrl: 'https://pa.watford.gov.uk/publicaccess' },
  { id: 'canterbury', name: 'Canterbury', baseUrl: 'https://pa.canterbury.gov.uk/online-applications' },
  { id: 'dartford', name: 'Dartford', baseUrl: 'https://publicaccess.dartford.gov.uk/online-applications' },
  { id: 'thanet', name: 'Thanet', baseUrl: 'https://planning.thanet.gov.uk/online-applications' },
  { id: 'tonbridge', name: 'Tonbridge', baseUrl: 'https://publicaccess.tmbc.gov.uk/online-applications' },
  { id: 'tunbridge-wells', name: 'Tunbridge Wells', baseUrl: 'https://twbcpa.midkent.gov.uk/online-applications' },
  { id: 'rossendale', name: 'Rossendale', baseUrl: 'https://publicaccess.rossendale.gov.uk/online-applications' },
  { id: 'south-ribble', name: 'South Ribble', baseUrl: 'https://publicaccess.southribble.gov.uk/online-applications' },
  { id: 'west-lancashire', name: 'West Lancashire', baseUrl: 'https://pa.westlancs.gov.uk/online-applications' },
  { id: 'wyre', name: 'Wyre', baseUrl: 'https://publicaccess.wyre.gov.uk/online-applications' },
  { id: 'blaby', name: 'Blaby', baseUrl: 'https://pa.blaby.gov.uk/online-applications' },
  { id: 'harborough', name: 'Harborough', baseUrl: 'https://pa2.harborough.gov.uk/online-applications' },
  { id: 'hinckley-and-bosworth', name: 'Hinckley and Bosworth', baseUrl: 'https://pa.hinckley-bosworth.gov.uk/online-applications' },
  { id: 'melton', name: 'Melton', baseUrl: 'https://pa.melton.gov.uk/online-applications' },
  { id: 'north-west-leicestershire', name: 'North West Leicestershire', baseUrl: 'https://plans.nwleics.gov.uk/public-access' },
  { id: 'oadby-and-wigston', name: 'Oadby and Wigston', baseUrl: 'https://pa.oadby-wigston.gov.uk/online-applications' },
  { id: 'east-lindsey', name: 'East Lindsey', baseUrl: 'https://publicaccess.e-lindsey.gov.uk/online-applications' },
  { id: 'lincoln', name: 'Lincoln', baseUrl: 'https://planning.lincoln.gov.uk/online-applications' },
  { id: 'north-kesteven', name: 'North Kesteven', baseUrl: 'https://planningonline.n-kesteven.gov.uk/online-applications' },
  { id: 'south-kesteven', name: 'South Kesteven', baseUrl: 'https://prod.publicaccess.southkesteven.gov.uk/online-applications' },
  { id: 'kings-lynn', name: 'Kings Lynn', baseUrl: 'https://online.west-norfolk.gov.uk/online-applications' },
  { id: 'north-norfolk', name: 'North Norfolk', baseUrl: 'https://idoxpa.north-norfolk.gov.uk/online-applications' },
  { id: 'norwich', name: 'Norwich', baseUrl: 'https://planning.norwich.gov.uk/online-applications' },
  { id: 'craven', name: 'Craven', aliases: ['Harrogate', 'Scarborough', 'North Yorkshire'], baseUrl: 'https://publicaccess.northyorks.gov.uk/online-applications' },
  { id: 'hambleton', name: 'Hambleton', baseUrl: 'https://planning.hambleton.gov.uk/online-applications' },
  { id: 'basingstoke', name: 'Basingstoke', baseUrl: 'https://planning.basingstoke.gov.uk/online-applications' },
  { id: 'dover', name: 'Dover', baseUrl: 'https://publicaccess.dover.gov.uk/online-applications' },
  { id: 'gravesham', name: 'Gravesham', baseUrl: 'https://plan.gravesham.gov.uk/online-applications' },
  { id: 'sevenoaks', name: 'Sevenoaks', baseUrl: 'https://pa.sevenoaks.gov.uk/online-applications' },
  { id: 'chorley', name: 'Chorley', baseUrl: 'https://planning.chorley.gov.uk/online-applications' },
  { id: 'lancaster', name: 'Lancaster', baseUrl: 'https://planning.lancaster.gov.uk/online-applications' },
  { id: 'pendle', name: 'Pendle', baseUrl: 'https://publicaccess.pendle.gov.uk/online-applications' },
  { id: 'richmondshire', name: 'Richmondshire', baseUrl: 'https://planning.richmondshire.gov.uk/online-applications' },
  { id: 'ryedale', name: 'Ryedale', baseUrl: 'https://planningregister.ryedale.gov.uk/caonline-applications' },
  { id: 'west-oxfordshire', name: 'West Oxfordshire', baseUrl: 'https://publicaccess.westoxon.gov.uk/online-applications' },
  { id: 'mendip', name: 'Mendip', baseUrl: 'https://publicaccess.mendip.gov.uk/online-applications' },
  { id: 'south-somerset', name: 'South Somerset', baseUrl: 'https://publicaccess.southsomerset.gov.uk/online-applications' },
  { id: 'west-somerset', name: 'West Somerset', baseUrl: 'https://www1.somersetwestandtaunton.gov.uk/online-applications' },
  { id: 'lichfield', name: 'Lichfield', baseUrl: 'https://planning.lichfielddc.gov.uk/online-applications' },
  { id: 'newcastle-under-lyme', name: 'Newcastle under Lyme', baseUrl: 'https://publicaccess.newcastle-staffs.gov.uk/online-applications' },
  { id: 'south-staffordshire', name: 'South Staffordshire', baseUrl: 'https://planning.sstaffs.gov.uk/online-applications' },
  { id: 'stafford', name: 'Stafford', baseUrl: 'https://www12.staffordbc.gov.uk/online-applications' },
  { id: 'epsom-and-ewell', name: 'Epsom and Ewell', baseUrl: 'https://eplanning.epsom-ewell.gov.uk/online-applications' },
  { id: 'guildford', name: 'Guildford', baseUrl: 'https://publicaccess.guildford.gov.uk/online-applications' },
  { id: 'spelthorne', name: 'Spelthorne', baseUrl: 'https://publicaccess.spelthorne.gov.uk/online-applications' },
  { id: 'surrey-heath', name: 'Surrey Heath', baseUrl: 'https://publicaccess.surreyheath.gov.uk/online-applications' },
  { id: 'woking', name: 'Woking', baseUrl: 'https://caps.woking.gov.uk/online-applications' },
  { id: 'warwick', name: 'Warwick', baseUrl: 'https://planningdocuments.warwickdc.gov.uk/online-applications' },
  { id: 'chichester', name: 'Chichester', baseUrl: 'https://publicaccess.chichester.gov.uk/online-applications' },
  { id: 'horsham', name: 'Horsham', baseUrl: 'https://public-access.horsham.gov.uk/public-access' },
  { id: 'wigan', name: 'Wigan', baseUrl: 'https://planning.wigan.gov.uk/online-applications' },
  { id: 'selby', name: 'Selby', baseUrl: 'https://public.selby.gov.uk/online-applications' },
  { id: 'bassetlaw', name: 'Bassetlaw', baseUrl: 'https://publicaccess.bassetlaw.gov.uk/online-applications' },
  { id: 'broxtowe', name: 'Broxtowe', baseUrl: 'https://publicaccess.broxtowe.gov.uk/online-applications' },
  { id: 'gedling', name: 'Gedling', baseUrl: 'https://pawam.gedling.gov.uk/online-applications' },
  { id: 'mansfield', name: 'Mansfield', baseUrl: 'https://planning.mansfield.gov.uk/online-applications' },
  { id: 'newark-and-sherwood', name: 'Newark and Sherwood', baseUrl: 'https://publicaccess.newark-sherwooddc.gov.uk/online-applications' },
  { id: 'rushcliffe', name: 'Rushcliffe', baseUrl: 'https://planningon-line.rushcliffe.gov.uk/online-applications' },
  { id: 'oxford', name: 'Oxford', baseUrl: 'https://public.oxford.gov.uk/online-applications' },
  { id: 'reigate', name: 'Reigate', baseUrl: 'https://planning.reigate-banstead.gov.uk/online-applications' },
  { id: 'knowsley', name: 'Knowsley', baseUrl: 'https://planapp.knowsley.gov.uk/online-applications' },
  { id: 'st-helens', name: 'St Helens', baseUrl: 'https://publicaccess.sthelens.gov.uk/online-applications' },
  { id: 'sefton', name: 'Sefton', baseUrl: 'https://pa.sefton.gov.uk/online-applications' },
  { id: 'doncaster', name: 'Doncaster', baseUrl: 'https://planning.doncaster.gov.uk/online-applications' },
  { id: 'sheffield', name: 'Sheffield', baseUrl: 'https://planningapps.sheffield.gov.uk/online-applications' },
  { id: 'gateshead', name: 'Gateshead', baseUrl: 'https://public.gateshead.gov.uk/online-applications' },
  { id: 'north-tyneside', name: 'North Tyneside', baseUrl: 'https://idoxpublicaccess.northtyneside.gov.uk/online-applications' },
  { id: 'sunderland', name: 'Sunderland', baseUrl: 'https://online-applications.sunderland.gov.uk/online-applications' },
  { id: 'sandwell', name: 'Sandwell', baseUrl: 'https://webcaps.sandwell.gov.uk/publicaccess' },
  { id: 'solihull', name: 'Solihull', baseUrl: 'https://publicaccess.solihull.gov.uk/online-applications' },
  { id: 'wolverhampton', name: 'Wolverhampton', baseUrl: 'https://planningonline.wolverhampton.gov.uk/online-applications' },
  { id: 'leeds', name: 'Leeds', baseUrl: 'https://publicaccess.leeds.gov.uk/online-applications' },
  { id: 'wakefield', name: 'Wakefield', baseUrl: 'https://planning.wakefield.gov.uk/online-applications' },
  { id: 'city', name: 'City', baseUrl: 'https://www.planning2.cityoflondon.gov.uk/online-applications' },
  { id: 'barnet', name: 'Barnet', baseUrl: 'https://publicaccess.barnet.gov.uk/online-applications' },
  { id: 'bexley', name: 'Bexley', baseUrl: 'https://pa.bexley.gov.uk/online-applications' },
  { id: 'brent', name: 'Brent', baseUrl: 'https://pa.brent.gov.uk/online-applications' },
  { id: 'croydon', name: 'Croydon', baseUrl: 'https://publicaccess3.croydon.gov.uk/online-applications' },
  { id: 'ealing', name: 'Ealing', baseUrl: 'https://pam.ealing.gov.uk/online-applications' },
  { id: 'enfield', name: 'Enfield', baseUrl: 'https://planningandbuildingcontrol.enfield.gov.uk/online-applications' },
  { id: 'greenwich', name: 'Greenwich', baseUrl: 'https://planning.royalgreenwich.gov.uk/online-applications' },
  { id: 'kingston', name: 'Kingston', baseUrl: 'https://publicaccess.kingston.gov.uk/online-applications' },
  { id: 'lambeth', name: 'Lambeth', baseUrl: 'https://planning.lambeth.gov.uk/online-applications' },
  { id: 'lewisham', name: 'Lewisham', baseUrl: 'https://planning.lewisham.gov.uk/online-applications' },
  { id: 'mid-sussex', name: 'Mid Sussex', baseUrl: 'https://pa.midsussex.gov.uk/online-applications' },
  { id: 'falkirk', name: 'Falkirk', baseUrl: 'https://edevelopment.falkirk.gov.uk/online' },
  { id: 'wyre-forest', name: 'Wyre Forest', baseUrl: 'https://planningpa.wyreforestdc.gov.uk/online-applications' },
  { id: 'bolton', name: 'Bolton', baseUrl: 'https://paplanning.bolton.gov.uk/online-applications' },
  { id: 'bury', name: 'Bury', baseUrl: 'https://planning.bury.gov.uk/online-applications' },
  { id: 'oldham', name: 'Oldham', baseUrl: 'https://planningpa.oldham.gov.uk/online-applications' },
  { id: 'stockport', name: 'Stockport', baseUrl: 'https://planning.stockport.gov.uk/PlanningData-live' },
  { id: 'tameside', name: 'Tameside', baseUrl: 'https://publicaccess.tameside.gov.uk/online-applications' },
  { id: 'trafford', name: 'Trafford', baseUrl: 'https://publicaccess.trafford.gov.uk/online-applications' },
  { id: 'bradford', name: 'Bradford', baseUrl: 'https://planning.bradford.gov.uk/online-applications' },
  { id: 'calderdale', name: 'Calderdale', baseUrl: 'https://portal.calderdale.gov.uk/online-applications' },
  { id: 'newham', name: 'Newham', baseUrl: 'https://pa.newham.gov.uk/online-applications' },
  { id: 'southwark', name: 'Southwark', baseUrl: 'https://planning.southwark.gov.uk/online-applications' },
  { id: 'sutton', name: 'Sutton', baseUrl: 'https://planningregister.sutton.gov.uk/online-applications' },
  { id: 'tower-hamlets', name: 'Tower Hamlets', baseUrl: 'https://development.towerhamlets.gov.uk/online-applications' },
  { id: 'westminster', name: 'Westminster', baseUrl: 'https://idoxpa.westminster.gov.uk/online-applications' },
  { id: 'buckinghamshire', name: 'Buckinghamshire', baseUrl: 'https://publicaccess.buckinghamshire.gov.uk/online-applications' },
  { id: 'broads', name: 'Broads', baseUrl: 'https://planning.broads-authority.gov.uk/online-applications' },
  { id: 'midlothian', name: 'Midlothian', baseUrl: 'https://planning-applications.midlothian.gov.uk/OnlinePlanning' },
  { id: 'moray', name: 'Moray', baseUrl: 'https://publicaccess.moray.gov.uk/eplanning' },
  { id: 'north-ayrshire', name: 'North Ayrshire', baseUrl: 'https://www.eplanning.north-ayrshire.gov.uk/OnlinePlanning' },
  { id: 'orkney', name: 'Orkney', baseUrl: 'https://planningandwarrant.orkney.gov.uk/online-applications' },
  { id: 'perth', name: 'Perth', baseUrl: 'https://planningapps.pkc.gov.uk/online-applications' },
  { id: 'scottish-borders', name: 'Scottish Borders', baseUrl: 'https://eplanning.scotborders.gov.uk/online-applications' },
  { id: 'shetlands', name: 'Shetlands', baseUrl: 'https://pa.shetland.gov.uk/online-applications' },
  { id: 'south-ayrshire', name: 'South Ayrshire', baseUrl: 'https://publicaccess.south-ayrshire.gov.uk/online-applications' },
  { id: 'south-lanarkshire', name: 'South Lanarkshire', baseUrl: 'https://publicaccess.southlanarkshire.gov.uk/online-applications' },
  { id: 'argyll', name: 'Argyll', baseUrl: 'https://publicaccess.argyll-bute.gov.uk/online-applications' },
  { id: 'edinburgh', name: 'Edinburgh', baseUrl: 'https://citydev-portal.edinburgh.gov.uk/idoxpa-web' },
  { id: 'renfrewshire', name: 'Renfrewshire', baseUrl: 'https://pl-bs.renfrewshire.gov.uk/online-applications' },
  { id: 'north-lanarkshire', name: 'North Lanarkshire', baseUrl: 'https://eplanning.northlanarkshire.gov.uk/online-applications' },
  { id: 'east-dunbartonshire', name: 'East Dunbartonshire', baseUrl: 'https://planning.eastdunbarton.gov.uk/online-applications' },
  { id: 'glasgow', name: 'Glasgow', baseUrl: 'https://publicaccess.glasgow.gov.uk/online-applications' },
  { id: 'south-downs', name: 'South Downs', baseUrl: 'https://planningpublicaccess.southdowns.gov.uk/online-applications' },
  { id: 'clackmannanshire', name: 'Clackmannanshire', baseUrl: 'https://publicaccess.clacks.gov.uk/publicaccess' },
  { id: 'fife', name: 'Fife', baseUrl: 'https://planning.fife.gov.uk/online' },
  { id: 'highland', name: 'Highland', baseUrl: 'https://wam.highland.gov.uk/wam' },
  { id: 'inverclyde', name: 'Inverclyde', baseUrl: 'https://planning.inverclyde.gov.uk/Online' },
  { id: 'dumfries', name: 'Dumfries', baseUrl: 'https://eaccess.dumgal.gov.uk/online-applications' },
  { id: 'east-ayrshire', name: 'East Ayrshire', baseUrl: 'https://eplanning.east-ayrshire.gov.uk/online' },
  { id: 'east-lothian', name: 'East Lothian', baseUrl: 'https://pa.eastlothian.gov.uk/online-applications' },
  { id: 'east-renfrewshire', name: 'East Renfrewshire', baseUrl: 'https://ercbuildingstandards.eastrenfrewshire.gov.uk/buildingstandards' },
  { id: 'western-isles', name: 'Western Isles', baseUrl: 'https://planning.cne-siar.gov.uk/PublicAccess' },
  { id: 'loch-lomond', name: 'Loch Lomond', baseUrl: 'https://eplanning.lochlomond-trossachs.org/OnlinePlanning' },
  { id: 'cairngorms', name: 'Cairngorms', baseUrl: 'https://www.eplanningcnpa.co.uk/online-applications' },
  { id: 'swansea', name: 'Swansea', baseUrl: 'https://property.swansea.gov.uk/online-applications' },
  { id: 'neath', name: 'Neath', baseUrl: 'https://planningonline.npt.gov.uk/online-applications' },
  { id: 'cardiff', name: 'Cardiff', baseUrl: 'https://www.cardiffidoxcloud.wales/publicaccess' },
  { id: 'rhondda', name: 'Rhondda', baseUrl: 'https://planonline.rctcbc.gov.uk/online-applications' },
  { id: 'caerphilly', name: 'Caerphilly', baseUrl: 'https://publicaccess.caerphilly.gov.uk/PublicAccess' },
  { id: 'torfaen', name: 'Torfaen', baseUrl: 'https://planningonline.torfaen.gov.uk/online-applications' },
  { id: 'monmouthshire', name: 'Monmouthshire', baseUrl: 'https://planningonline.monmouthshire.gov.uk/online-applications' },
  { id: 'newport', name: 'Newport', baseUrl: 'https://publicaccess.newport.gov.uk/online-applications' },
  { id: 'merthyr-tydfil', name: 'Merthyr Tydfil', baseUrl: 'https://publicaccess.merthyr.gov.uk/online-applications' },
  { id: 'brecon-beacons', name: 'Brecon Beacons', baseUrl: 'https://planningonline.beacons-npa.gov.uk/online-applications' },
  { id: 'stirling', name: 'Stirling', baseUrl: 'https://pabs.stirling.gov.uk/online-applications' },
  { id: 'aberdeen', name: 'Aberdeen', baseUrl: 'https://publicaccess.aberdeencity.gov.uk/online-applications' },
  { id: 'aberdeenshire', name: 'Aberdeenshire', baseUrl: 'https://upa.aberdeenshire.gov.uk/online-applications' },
  { id: 'west-lothian', name: 'West Lothian', baseUrl: 'https://planning.westlothian.gov.uk/publicaccess' },
  { id: 'angus', name: 'Angus', baseUrl: 'https://planning.angus.gov.uk/online-applications' },
  { id: 'dundee', name: 'Dundee', baseUrl: 'https://idoxwam.dundeecity.gov.uk/idoxpa-web' },
  { id: 'adur-and-worthing', name: 'Adur and Worthing', baseUrl: 'https://planning.adur-worthing.gov.uk/online-applications' },
  { id: 'isle-of-man', name: 'Isle of Man', baseUrl: 'https://pbc.gov.im/online-applications' },
  { id: 'west-suffolk', name: 'West Suffolk', baseUrl: 'https://planning.westsuffolk.gov.uk/online-applications' },
  { id: 'mid-ulster', name: 'Mid Ulster', baseUrl: 'https://planning.midulstercouncil.org/online-applications' },
  { id: 'mid-kent', name: 'Mid Kent', baseUrl: 'https://pa.midkent.gov.uk/online-applications' },
  { id: 'east-suffolk', name: 'East Suffolk', baseUrl: 'https://publicaccess.eastsuffolk.gov.uk/online-applications' },
  { id: 'babergh-mid-suffolk', name: 'Babergh Mid Suffolk', baseUrl: 'https://planning.baberghmidsuffolk.gov.uk/online-applications' },
  { id: 'bromsgrove-redditch', name: 'Bromsgrove Redditch', baseUrl: 'https://publicaccess.bromsgroveandredditch.gov.uk/online-applications' },
  { id: 'chiltern-south-bucks', name: 'Chiltern South Bucks', baseUrl: 'https://pa-csb.buckinghamshire.gov.uk/online-applications' },
  { id: 'north-northamptonshire', name: 'North Northamptonshire', baseUrl: 'https://publicaccess.northnorthants.gov.uk/online-applications' },
  { id: 'south-norfolk-broadland', name: 'South Norfolk Broadland', baseUrl: 'https://info.southnorfolkandbroadland.gov.uk/online-applications' },
];

export function resolveAuthority(idOrName: string | undefined | null): AuthorityConfig {
  if (!idOrName || idOrName.trim() === '') {
    return getAuthority(DEFAULT_AUTHORITY_ID);
  }
  const key = idOrName.trim().toLowerCase();
  const found = AUTHORITIES.find(
    (a) =>
      a.id === key ||
      a.name.toLowerCase() === key ||
      (a.aliases ?? []).some((alias) => alias.toLowerCase() === key)
  );
  if (found) return found;
  throw new Error(
    `Unknown planning authority "${idOrName}". Supported authorities: ${AUTHORITIES.map((a) => a.id).join(', ')}`
  );
}

export function isKnownAuthority(idOrName: string | undefined | null): boolean {
  if (!idOrName || idOrName.trim() === '') return false;
  const key = idOrName.trim().toLowerCase();
  return AUTHORITIES.some(
    (a) =>
      a.id === key ||
      a.name.toLowerCase() === key ||
      (a.aliases ?? []).some((alias) => alias.toLowerCase() === key)
  );
}

export function getAuthority(id: string): AuthorityConfig {
  const found = AUTHORITIES.find((a) => a.id === id);
  if (!found) throw new Error(`Unknown authority id "${id}"`);
  return found;
}

export function authorityName(authorityId?: string): string | undefined {
  if (!authorityId) return undefined;
  return AUTHORITIES.find((a) => a.id === authorityId)?.name;
}
